-- --CREAR TABLA DE POKEMONES

-- CREATE TABLE captured_pokemon
-- (
--    pokemonId INT GENERATED BY DEFAULT AS IDENTITY,
--    api_version TEXT,
--    name TEXT,
--    first_slot TEXT,
--    second_slot TEXT NULL,
--    img_url TEXT,
--    trainerId INT
-- );

-- --CREAR TABLA DE ENTRENADORES

-- CREATE TABLE pokemon_trainer
-- (
--     trainerId INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name TEXT,
--     last_name TEXT,
--     region TEXT NULL,
--     email TEXT NULL    
-- );

-- --Agregar el FK

-- ALTER TABLE captured_pokemon
-- ADD CONSTRAINT fk_trainer FOREIGN KEY(trainerId) 
-- REFERENCES pokemon_traineR(trainerId);

